[package]
name = "othello_ai"
version = "0.1.0"
authors = ["Luke Chu <37006668+lukechu10@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"

[profile.release]
debug = true